"""add_tables_for_time_management

Revision ID: 5376da082312
Revises: 81672306724d
Create Date: 2025-11-02 12:14:17.341510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5376da082312'
down_revision: Union[str, Sequence[str], None] = '81672306724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_sort_order'), 'plans', ['sort_order'], unique=False)
    op.create_table('act_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_act_notes_id'), 'act_notes', ['id'], unique=False)
    op.create_table('plan_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_notes_id'), 'plan_notes', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_sort_order'), 'tasks', ['sort_order'], unique=False)
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('STOPPED', 'COUNTING', 'PAUSED', name='timerstate'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    op.create_table('times',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('count', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('day', 'act_id')
    )
    op.add_column('acts', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('acts', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_acts_sort_order'), 'acts', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acts_sort_order'), table_name='acts')
    op.drop_column('acts', 'sort_order')
    op.drop_column('acts', 'hidden')
    op.drop_table('times')
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_tasks_sort_order'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_plan_notes_id'), table_name='plan_notes')
    op.drop_table('plan_notes')
    op.drop_index(op.f('ix_act_notes_id'), table_name='act_notes')
    op.drop_table('act_notes')
    op.drop_index(op.f('ix_plans_sort_order'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
